### ISSUE TITLE
Docker container crash when install using the Docker way

### ISSUE THREAD

**Issue by Dynnammo** [ClaperCo/Claper#21]
**Context**
As an admin sys, I would like to test Claper on my local machine before installing it for my company

**Describe the bug**
Steps to reproduce

1. Launch docker container : `  docker run -p 5432:5432 -e POSTGRES_PASSWORD=claper -e POSTGRES_USER=claper -e POSTGRES_DB=claper --name claper-db -d postgres:9` (works fine)
2. Build claper container : `docker build -t claper .` (works fine)
3. Launch claper container : `docker run -p 4000:4000 -d claper`
⇒ Crashes with this message

```shell
ERROR! Config provider Config.Reader failed with:
{"init terminating in do_boot",{#{'__exception__'=>true,'__struct__'=>'Elixir.RuntimeError',message=><<101,110,118,105,114,111,110,109,101,110,116,32,118,97,114,105,97,98,108,101,32,68,65,84,65,66,65,83,69,95,85,82,76,32,105,115,32,109,105,115,115,105,110,103,46,10,70,111,114,32,101,120,97,109,112,108,101,58,32,101,99,116,111,58,47,47,85,83,69,82,58,80,65,83,83,64,72,79,83,84,47,68,65,84,65,66,65,83,69,10>>},[{erl_eval,do_apply,6,[{file,"erl_eval.erl"},{line,685},{error_info,#{module=>'Elixir.Exception'}}]},{erl_eval,expr,5,[{file,"erl_eval.erl"},{line,446}]},{erl_eval,exprs,5,[{file,"erl_eval.erl"},{line,123}]},{elixir,recur_eval,3,[{file,"src/elixir.erl"},{line,289}]},{elixir,eval_forms,3,[{file,"src/elixir.erl"},{line,274}]},{'Elixir.Code',validated_eval_string,3,[{file,"lib/code.ex"},{line,404}]},{'Elixir.Config','__eval__!',3,[{file,"lib/config.ex"},{line,260}]},{'Elixir.Config.Reader','read!',2,[{file,"lib/config/reader.ex"},{line,92}]}]}}
init terminating in do_boot ({,[{erl_eval,do_apply,6,[{_},{_},{_}]},{erl_eval,expr,5,[{_},{_}]},{erl_eval,exprs,5,[{_},{_}]},{elixir,recur_eval,3,[{_},{_}]},{elixir,eval_forms,3,[{_},{_}]},{Elixir.Code,validated_eval_string,3,[{_},{_}]},{Elixir.Config,__eval__!,3,[{_},{_}]},{Elixir.Config.Reader,read!,2,[{_},{_}]}]})
** (RuntimeError) environment variable DATABASE_URL is missing.
For example: ecto://USER:PASS@HOST/DATABASE

    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
    (stdlib 3.17) erl_eval.erl:446: :erl_eval.expr/5
    (stdlib 3.17) erl_eval.erl:123: :erl_eval.exprs/5
    (elixir 1.13.2) src/elixir.erl:289: :elixir.recur_eval/3
    (elixir 1.13.2) src/elixir.erl:274: :elixir.eval_forms/3
    (elixir 1.13.2) lib/code.ex:404: Code.validated_eval_string/3
    (elixir 1.13.2) lib/config.ex:260: Config.__eval__!/3
    (elixir 1.13.2) lib/config/reader.ex:92: Config.Reader.read!/2


Crash dump is being written to: erl_crash.dump...done
```

From what I see, the container do not detect the Postgres database anywhere.

**Other information**
- OS : Manjaro Linux

This issue seems to be linked to the Docker containerization solely, since I tried the Elixir install using `mix` and I worked fine :tada:

**Comment by alxlion** [comment]
Do not forget to set the environment variables in the docker run command with `docker run -e DATABASE_URL=claper-db -e MAIL=local ...`.

I'll add this information in the documentation for the next time. 

Thanks for your report
