### ISSUE TITLE
Docker does not run. 

### ISSUE THREAD

**Issue by lordbagel42** [ClaperCo/Claper#24]
The following is an error when I try to run `docker run -e DATABASE_URL=claper-db -e SECRET_KEY_BASE=key -p 4000:4000 claper`

```
(Ecto.InvalidURLError) invalid url claper-db, host is not present. The parsed URL is: %URI{authority: nil, fragment: nil, host: nil, path: "claper-db", port: nil, query: nil, scheme: nil, userinfo: nil}
    lib/ecto/repo/supervisor.ex:92: Ecto.Repo.Supervisor.parse_url/1
    lib/ecto/repo/supervisor.ex:28: Ecto.Repo.Supervisor.runtime_config/4
    (claper 1.2.0) lib/claper/repo.ex:2: Claper.Repo.config/0
    lib/ecto/migrator.ex:126: Ecto.Migrator.with_repo/3
    (claper 1.2.0) lib/claper/release.ex:14: anonymous fn/2 in Claper.Release.migrate/0
    (elixir 1.13.2) lib/enum.ex:2396: Enum."-reduce/3-lists^foldl/2-0-"/3
    (claper 1.2.0) lib/claper/release.ex:13: Claper.Release.migrate/0
    (stdlib 3.17) erl_eval.erl:685: :erl_eval.do_apply/6
```

**Comment by lordbagel42** [comment]
docker-compose is much better, I would recommend removing the other info from the docs and just saying to use docker-compose.
